### ISSUE TITLE
How to create synthetic ground truth images

### ISSUE THREAD

**Issue by OhkumaTakumi** [wangguanzhi/LADN#2]
The traning dataset includes synthetic ground truth. However when I would like to add the new images to the dataset, I cannot prepare synthetic ground truth for new images. So would you tell me how to create synthetic ground truth?

**Comment by georgegu1997** [comment]
Thanks for the question! 

Since the libraries required for generating synthetic ground truth has conflicts with those for training, we didn't include the script for synthesizing in this repo. We will update them in another repo later. 

The overall pipeline is facial landmark detection (we used Face++ API together with PyStasm) -> face cropping and warping ([Face Morpher](https://github.com/alyssaq/face_morpher)) -> image blending (Poisson blending) -> some heuristic to enhance the generated colour.

**Comment by OhkumaTakumi** [comment]
Thank you for reply and your great work!

I'm waiting you update the code for ground truth in another repo.

**Comment by cwzcwz** [comment]
@georgegu1997  hello，Is this problem solved ? I also want to know how to get  the synthetic ground truth.

**Comment by DanielMao2015** [comment]
@georgegu1997 What kind of the heuristic way is your pipeline to enhance the generated colour? Since I use the face morpher mentioned above but the result seems to not be similar with that of your released dataset.

**Comment by sywh** [comment]
Waiting for the code of synthesizing ground truth, too...

**Comment by cailk** [comment]
@georgegu1997 Hi! Sorry to bother. I would like to know when will the code for synthesizing ground truth be released?

**Comment by georgegu1997** [comment]
Sincere apologies for such a long delay. The code for synthetic ground truth is updated [here](https://github.com/georgegu1997/makeup-transfer-public).  Hope this is still helpful to you guys.
